server:
  port: 8090

spring:
  application:
    name: msvc-users
  datasource:
    url: jdbc:mysql://yamabiko.proxy.rlwy.net:19992/railway
    username: root
    password: LxizxLpXgHkGpHdXZxinQNagbrfrFJeD
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop   # ? perfecto para pruebas, borra y recrea
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

# Desactiva mientras no tengas Config Server
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
